CREATE TABLE Users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	pseudo VARCHAR(50) NOT NULL, 
	mdp VARCHAR(60) NOT NULL, 
	connected BOOL NOT NULL DEFAULT
)

CREATE TABLE Capteurs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	type VARCHAR(255) NOT NULL,
	TramJson TEXT,
)